### ISSUE TITLE
Consider merging the two binaries

### ISSUE THREAD

**Issue by tomhoule** [store2be/pape-rs#114]
This would be an improvement because:

- More consistent versions
- Faster build times
- We would know where to add new functionality like merge

I propose organizing options like this:

- `papers run` just runs the service
- `papers test` is the current papers-local
- `papers merge` is a local merge test tool

**Comment by brainlessdeveloper** [comment]
`papers preview` could show the rendered template?

**Comment by tomhoule** [comment]
That would be easy to implement, yes. `papers-local` already writes the rendered template to `rendered.tex`.

**Comment by brainlessdeveloper** [comment]
Maybe we could do this gradually and implement the three modes in different PRs and then remove dead code in the last one?

**Comment by tomhoule** [comment]
That would be possible, yes, but code would have to be duplicated or moved out of papers-local (at which point it may make sense to already delete it completely).

**Comment by tomhoule** [comment]
https://github.com/store2be/pape-rs/pull/122/files

**Comment by tomhoule** [comment]
This needs to be documented.

**Comment by tomhoule** [comment]
This is documented in the README.
